#pragma once

#define WM_APP_ADD_JAR_SCAN_ITEM (WM_APP + 1)
#define WM_APP_JAR_SCAN_COMPLETE (WM_APP + 2)
#define WM_APP_GLOBAL_SEARCH_ADD_ITEM (WM_APP + 3) 
#define WM_APP_GLOBAL_SEARCH_COMPLETE (WM_APP + 4)
#define WM_APP_JAR_BATCH_FOUND (WM_APP + 3)

#define ID_MENU_TOGGLE_DARK_MODE 40001
#define ID_MENU_COPY_NAME 5001
#define ID_MENU_COPY_PATH 5002
#define ID_MENU_COPY_METHODS 5003
#define ID_MENU_COPY_ALL 5004
#define ID_MENU_COPY_CLASS_NAME 5005

#define ID_TAB_CONTROL 101
#define ID_BUTTON_JAR_SCAN 201
#define ID_LISTVIEW_MAVEN 202
#define ID_LISTVIEW_GRADLE 203
#define ID_LISTVIEW_FORGE 204
#define ID_LISTVIEW_FABRIC 205
#define ID_LISTVIEW_MCP 206
#define ID_LISTVIEW_LIBS 207
#define ID_LISTVIEW_RUNNABLEJARS 208
#define ID_SEARCH_MAVEN 252
#define ID_SEARCH_GRADLE 253
#define ID_SEARCH_FORGE 254
#define ID_SEARCH_FABRIC 255
#define ID_SEARCH_MCP 256
#define ID_SEARCH_LIBS 257
#define ID_SEARCH_RUNNABLEJARS 258
#define ID_NIJIKA_IMAGE 270
#define ID_BUTTON_GLOBAL_CLASS_SEARCH 271
#define ID_GLOBAL_SEARCH_EDIT 272
#define ID_GLOBAL_SEARCH_BUTTON 273
#define ID_GLOBAL_SEARCH_LIST 274
#define ID_SORT_COMBO 280
#define ID_FILTER_COMBO 281
#define ID_STATIC_TITLE 290
#define ID_STATIC_DESC 291
#define ID_CHECKBOX_MULTITHREAD 292
#define ID_BUTTON_OPEN 301
#define ID_LISTVIEW_CLASSES 302
#define ID_SEARCH_CLASSES 352
#define ID_ENTROPY_LABEL 353
#define ID_BUTTON_JOURNAL 303
#define ID_LISTVIEW_JOURNAL 304
#define ID_SEARCH_JOURNAL 354
#define ID_BUTTON_RECENT 305
#define ID_LISTVIEW_RECENT 306
#define ID_SEARCH_RECENT 356
#define ID_BUTTON_PREFETCH 307
#define ID_LISTVIEW_PREFETCH 308
#define ID_SEARCH_PREFETCH 358
#define ID_BUTTON_PROCESS_SCAN 309
#define ID_LISTVIEW_PROCESSES 310
#define ID_SEARCH_PROCESSES 360